---
title: Going crazy over social impact
date: '2009-11-18'
tags: []
wp:post_id: '1041'
link: http://island94.dev/2009/11/going-crazy-over-social-impact/
wp:post_type: post
---

<p>This week's topic in the Millenial Blogging Alliance is "How do you define and measure Social Impact?" Since I'm currently at 34,000 feet and salty about some recent Federal funding restrictions, let's go a little crazy.</p>
<p> I am hereby defining Social Impact as the flow of dollars between your community and the outside world. Positive Social Impact is a net increase in dollars within your community as a result of your activities. Negative Social Impact is a net decrease in dollars within your community as a result of your activities.</p>
<p>That's even easy to measure, unless it's indirect. And it's the indirect impact that's the problem. Providing services does not bring money into your community, unless:</p>
<p>- you and your staff are part of that community e.g. you are your constituents if identity based, or within the physical area if you are geographically based, or a some proportion of  the two<br />
- the supplies you're using are produced by your community, proportional to community ownership and labor<br />
- the supplies are sold by the community, in which case you can only include the retail markup as impactful if they were manufactured elsewhere, and only that being proportional to community ownership and labor<br />
- your activities somehow induce money to enter the community now or at some later date</p>
<p>And don't forget to subtract earned income if those funds pay staff from outside the community, or purchase supplies that were sold or manufactured elsewhere.</p>
<p>So I must be arguing for direct grants. I am. And does that undermine the nonprofit service model? It does. We have been operating under the idea that if the "services" present in affluent communities are replicated in impoverished communities, then those communities will have the opportunity to become affluent. This is putting the cart before the horse: those businesses, services and public spaces did not create the affluence; they are a result of it.</p>
<p>In response to the "personal responsibility" criticisms: the goal is not is not to induce any one particular person to work, it's about creating an environment in which people can work, be paid for their work, and contribute towards building their community. The way to allow that to happen is ensure that people can easily exchange labor, goods and services. To do that, you need money. Our communities are poor not because they cannot circulate money, but that they have little or no money to begin with.</p>
<p>This concept of social impact embraces the ideal that people want to work and contribute to their community. We did not invent jobs as a way to spend money. We invented money to improve the efficiency of coordinating our collective efforts and outputs. This is not to say that money should be the <em>measure</em> of the <em>quality</em> of our communities; those metrics should be up to the community to decide--but communities should have the tool, money, to build the place in which they wish to live.</p>
<p>And yes, I am aware of alternative currencies, but they're few and far between. The true aspiration here is providing individuals, to the fullest extent of society, the agency to create the world in which they wish to live. But I can't fully describe that, let alone measure it, without stepping outside of Wealth Bondage. Then again, I did say I'd go crazy.</p>
<p>So if you want to look at your social impact, follow the money.</p>
<p>Updated: Read the other posts in the Millenial Blogger Alliance:</p>
<p>Rosetta, <a href="http://rosettathurman.com/blog/2009/11/working-at-a-nonprofit-does-not-equal-social-change/">Working at a Nonprofit Does Not Equal Social Change</a><br style="padding: 0px; margin: 0px;" />Colleen, <a href="http://colleendilen.com/2009/11/12/does-writing-a-check-to-a-nonprofit-equal-social-change/">Does Writing a Check to a Nonprofit Equal Social Change?</a><br style="padding: 0px; margin: 0px;" />Elizabeth, <a href="http://nonprofitperiscope.wordpress.com/2009/11/16/what-is-social-impact/">What is Social Impact?<br style="padding: 0px; margin: 0px;" /></a>Elisa, <a href="http://elisamortiz.wordpress.com/2009/11/11/measuring-social-impact-wait%E2%80%A6what-is-social-impact/">Measuring Social Impact</a><br style="padding: 0px; margin: 0px;" />Tracey, <a href="http://www.blackgivesback.com/2009/11/meaning-of-social-impact.html">The Meaning of Social Impact</a><br style="padding: 0px; margin: 0px;" />James, <a href="http://jameselbaor.wordpress.com/2009/11/17/measuring-social-impact/">Measuring Social Impact</a><br style="padding: 0px; margin: 0px;" />Lauren,  <a href="http://alaurenabele.com/2009/11/how-do-you-define-and-measure-social-impact/">How Do You Define and Measure Social Impact?<br style="padding: 0px; margin: 0px;" /></a>Allison, <a href="http://entrylevelliving.wordpress.com/2009/11/17/five-problems-measure-social-change/">Five Problems With How We Measure Social Change</a></p>
