---
title: Criticism of Actor-Network Theory
date: '2010-01-01'
tags: []
wp:post_id: '1659'
link: http://island94.dev/2010/01/criticism-actor-network-theory/
wp:post_type: post
---

Once you have a basic definition, I find it easiest to learn about something through its criticisms: what is criticised is usually what is unique. This is the Wikipedia's <a href="http://en.wikipedia.org/wiki/Actor-network_theory#Some_criticism">criticism of Actor-Network Theory</a>, which was developed by <a href="http://www.island94.org/2010/01/modern-and-post-modern-science/">previously mentioned</a> Bruno Latour:
<blockquote>Actor-network theory insists on the <a title="Human agency" href="http://en.wikipedia.org/wiki/Human_agency">agency</a> of nonhumans. Critics maintain that such properties as <em>intentionality</em> fundamentally distinguish humans from animals or from "things". ANT scholars respond that (a) they do not attribute intentionality and similar properties to nonhumans; (b) their conception of <a title="Human agency" href="http://en.wikipedia.org/wiki/Human_agency">agency</a> does not presuppose intentionality; (c) they locate agency neither in human "subjects" nor in non-human "objects," but in heterogeneous associations of humans and nonhumans.

ANT has been criticized as amoral. <a title="Wiebe Bijker" href="http://en.wikipedia.org/wiki/Wiebe_Bijker">Wiebe Bijker</a> has responded to this criticism by stating that the amorality of ANT is not a necessity. Moral and political positions are possible, but one must first describe the network before taking up such positions.

Other critics have argued that ANT may imply that all actors are of equal importance in the network. This critique holds that ANT does not account for pre-existing structures, such as power, but rather sees these structures as emerging from the actions of actors within the network and their ability to align in pursuit of their interests. For this reason, ANT is sometimes seen as an attempt to re-introduce <a title="Whig history" href="http://en.wikipedia.org/wiki/Whig_history">Whig history</a> into <a title="Science and technology studies" href="http://en.wikipedia.org/wiki/Science_and_technology_studies">science and technology studies</a>; like the myth of the <a title="Heroic inventor (page does not exist)" href="http://en.wikipedia.org/w/index.php?title=Heroic_inventor&amp;action=edit&amp;redlink=1">heroic inventor</a>, ANT can be seen as an attempt to explain successful innovators by saying only that they were successful. In a similar vein ANT has been criticised as overly managerial in focus.

Some critics have argued that research based on ANT perspectives remains entirely descriptive and fails to provide explanations for social processes. ANT - like comparable social scientific methods - requires judgment calls from the researcher as to which actors are important within a network and which are not. Critics argue that the importance of particular actors cannot be determined in the absence of 'out-of-network' criteria. Similarly, others argue that Actor-Networks risk degenerating into endless chains of association (<a title="Six degrees of separation" href="http://en.wikipedia.org/wiki/Six_degrees_of_separation">six degrees of separation</a> - we are all networked to one another). Other research perspectives such as <a title="Social constructionism" href="http://en.wikipedia.org/wiki/Social_constructionism">social constructionism</a>, <a title="Social network theory" href="http://en.wikipedia.org/wiki/Social_network_theory">social network theory</a>, <a title="Normalization Process Theory" href="http://en.wikipedia.org/wiki/Normalization_Process_Theory">Normalization Process Theory</a>, <a title="Diffusion of Innovations" href="http://en.wikipedia.org/wiki/Diffusion_of_Innovations">Diffusion of Innovations</a> theory are held to be important alternatives to ANT approaches.

In a workshop called "Actor Network and After", <a title="Bruno Latour" href="http://en.wikipedia.org/wiki/Bruno_Latour">Bruno Latour</a> stated that there are four things wrong with actor-network theory: "actor", "network", "theory" and the hyphen. In a later book however (<em>Reassembling the Social: An Introduction to Actor-Network-Theory</em>), Latour reversed himself, accepting the wide use of the term, "<em>including</em> the hyphen" (Latour 2005:9). He also remarked how he had been helpfully reminded that the ANT acronym "was perfectly fit for a blind, myopic, workaholic, trail-sniffing, and collective traveler" (the <a title="Ant" href="http://en.wikipedia.org/wiki/Ant">ant</a>, Latour 2005:9) – qualitative hallmarks of actor-network epistemology.</blockquote>
The last one is my favorite.
